# Configurações do ambiente
language: ruby
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
  - master

# Build e testes
before_script:
- eval "$(ssh-agent -s)"
- ./script/0.key-install
- ./script/0.set-git-ssh
script: ./script/1.build-and-test && ./script/2.store-binaries
