# Configurações do ambiente
language: ruby
sudo: required
services:
  - docker
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
  - master

# Build e testes
before_script:
- eval "$(ssh-agent -s)"
- ./_script/0.key-install
- ./_script/0.configure-git
- ./_script/0.known-hosts
script: ./_script/ci-script
