---
# Metadados do site
title: Vaga Lume - Empoderando crianças na Amazônia
description: >-
  A Vaga Lume é uma associação sem fins lucrativos que promove a leitura
  e a gestão de bibliotecas comunitárias como espaço para compartilhar saberes.
keywords:
- Vaga Lume
- vagalume
- leitura
- crianças
- Amazônia
- mediação
- cultura local
- escuta
- empoderamento
- transformação social
- bibliotecas
# Compartilhamento em redes sociais
url: https://www.vagalume.org.br
share_image: assets/img/fb_op1.jpg
share_image_alt: Grupo de leitura com crianças da Amazônia
twitter_username: VagaLume_ONG
# Apontamentos para outros sites
url_antigo: http://arquivo.vagalume.org.br
url_doar: https://vagalume.colabore.org/inicial
# Video da home-page
home_video_id: xt2qJwwnH2U
home_video_titulo: Expedição Vaga Lume - 15 anos
# Dados do rodapé
contato:
  email: falecom@vagalume.org.br
  telefone: (11) 3032-6032
  endereco_1: Rua Aspicuelta, 678, Vila Madalena
  endereco_2: 05433-011 - São Paulo - SP
# Configurações da ferramenta
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
assets:
  compress:
    css: true
    js: true
  digest: true
  source_maps: false
plugins:
- jekyll-admin
- jekyll-assets
- jekyll-last-modified-at
- jekyll-sitemap
- liquid_pluralize
exclude:
- _*
- deploy_rsa*
- Gemfile*
- INSTALL.md
- Rakefile
- README.md
- vendor
include:
- .htaccess
sass:
  style: compressed
