title: Vaga Lume - Empoderando crianças na Amazônia
description: A Vaga Lume é uma associação sem fins lucrativos que promove a leitura
             e a gestão de bibliotecas comunitárias como espaço para compartilhar saberes.
keywords:
  - Vaga Lume
  - vagalume
  - leitura
  - crianças
  - Amazônia
  - mediação
  - cultura local
  - escuta
  - empoderamento
  - transformação social
  - bibliotecas

url: http://vagalume.org.br
twitter_username: VagaLume_ONG
share_image: assets/img/fb_op1.png
share_image_alt: Grupo de leitura com crianças da Amazônia

exclude: [deploy_rsa.enc, vendor, test, Gemfile, Gemfile.lock, Rakefile, README.md]
sass:
  style: compressed
